### ISSUE TITLE
Can't access location system

### ISSUE THREAD

**Issue by nedrichards** [flathub/org.gnome.Weather#1]
> nick@endless-nedr:~$ flatpak run org.gnome.Weather 
Gjs-Message: JS LOG: Failed to connect to GeoClue2 service: GDBus.Error:org.freedesktop.DBus.Error.AccessDenied: Agent rejected 'org.gnome.Weather' for user '1001'. Please ensure that 'org.gnome.Weather' has installed a valid org.gnome.Weather.desktop file.

This leads to the 'Automatic Location' button being disabled in the Places popover. Looks like a problem with sandboxing/the difference between org.gnome.Weather.Application and org.gnome.Weather.BackgroundService.

**Comment by gcampax** [comment]
I am tempted to call this a bug in the portal.
They should treat org.gnome.Weather.Application.desktop as valid because it has the right prefix.

@alexlarsson can you comment?

**Comment by hadess** [comment]
Could you test with this patch to gnome-weather? Geoclue expects the application ID passed to be the one of the application UI, meaning that, under Flatpak, the app ID would correspond to the Flatpak ID. This also makes sure that the application ID matches a real UI application and can be shown properly in the Privacy panel.

If that works, I'll open a new issue against Geoclue to document this a bit better there.

```diff
diff --git a/src/app/currentLocationController.js b/src/app/currentLocationController.js
index ea88800..c7ee32c 100644
--- a/src/app/currentLocationController.js
+++ b/src/app/currentLocationController.js
@@ -44,7 +44,7 @@ var CurrentLocationController = class CurrentLocationController {
 
     _startGeolocationService() {
         this._processStarted = true;
-        Geoclue.Simple.new(pkg.name,
+        Geoclue.Simple.new('org.gnome.Weather',
                            Geoclue.AccuracyLevel.CITY,
                            null,
                            this._onSimpleReady.bind(this));
```

Update: the app ID is `org.gnome.Weather` not `org.gnome.Weather.Application`.

**Comment by hadess** [comment]
CC @zeenix

**Comment by nedrichards** [comment]
I'll absolutely give that a go. Thanks!

**Comment by nedrichards** [comment]
This patch doesn't make a difference in my testing. I assume that geoclue is then testing to see if an actual desktop file matches that and finds that it doesn't.

**Comment by hadess** [comment]
The fix might also be to rename `org.gnome.Weather.Application` to just `org.gnome.Weather`. I won't be able to work on this soon, but if you have a chance to test it out...

**Comment by nedrichards** [comment]
Understood. I quickly tried the simple version from the flathub side but the naming is too tangled up, it'll need a proper patch.

**Comment by hadess** [comment]
FWIW, @matthiasclasen and @zeenix are reworking geoclue to be a portal, you'll want to discuss it with them.

**Comment by zeenix** [comment]
@nedrichards 

> This patch doesn't make a difference in my testing. I assume that geoclue is then testing to see if an actual desktop file matches that and finds that it doesn't.

Just FYI, this check is done by gnome-shell when authorizing apps.

**Comment by BrainBlasted** [comment]
With 3.32 the App ID is org.gnome.Weather in every spot. Automatic location seems to work now. Closing, please request a re-open if this still doesn't work.
