### ISSUE TITLE
Integration with Gnome Shell is not working

### ISSUE THREAD

**Issue by dac73** [flathub/org.gnome.Weather#5]
On Fedora Silverblue integration with Shell is not working e.g. no weather under calendar in top bar.

**Comment by alice-mkh** [comment]
mclasen told me before it's because gnome-shell tries to directly use Weather's (and Clocks') gsettings and when you're running them in Flatpak, their schemas aren't visible to host.

**Comment by BrainBlasted** [comment]
This should be fixed with 3.34 :)

**Comment by go-ten** [comment]
Hello,
Not working with 3.34 on Debian 10 Buster.

Thanks

**Comment by krashekspres** [comment]
Also not working on Silverblue 31 beta.

**Comment by motorto** [comment]
Can confirm it's not working on Fedora 34 silverblue
